spring:
  datasource:
    url:  jdbc:h2:tcp://localhost/~/weatherstyle
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      encoding: UTF-8
#      data-locations: classpath:h2/data.sql
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    show-sql: true


logging:
  level:
    org.hibernate.SQL : debug
    org.hibernate.orm.jdbc.bind: trace

file:
  path:  C:/images/





